// import type { ActivityLogPoint, User } from "../types";

// export const users: User[] = [
//   {
//     id: "123456",
//     name: "Angela Dairo",
//     email: "angeladairo@gmail.com",
//     avatarUrl: "/profile.jpg",
//     patientId: "487492",
//     lastActive: "10/12/2024",
//     reminderStatus: "Sent",
//     pillStatus: "Filled",
//     isActive: true,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Not yet" },
//       { id: "2", date: "Yesterday", status: "Logged" },
//       { id: "3", date: "13/05/2025", status: "Missed" },
//       { id: "4", date: "12/05/2025", status: "Missed" },
//       { id: "5", date: "11/05/2025", status: "Logged" },
//       { id: "6", date: "10/05/2025", status: "Logged" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "110 mg/dL",
//         water: "500 ml",
//         meal: "120 g",
//         heartRate: "720 bpm",
//         exercise: "3000 steps",
//         sleep: "6h 30m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "125 mg/dL",
//         water: "650 ml",
//         meal: "130 g",
//         heartRate: "780 bpm",
//         exercise: "2800 steps",
//         sleep: "7h 15m",
//       },
//       {
//         id: "5",
//         date: "01/07/2024",
//         glucose: "115 mg/dL",
//         water: "550 ml",
//         meal: "140 g",
//         heartRate: "760 bpm",
//         exercise: "2700 steps",
//         sleep: "7h 00m",
//       },
//       {
//         id: "6",
//         date: "02/07/2024",
//         glucose: "135 mg/dL",
//         water: "720 ml",
//         meal: "160 g",
//         heartRate: "790 bpm",
//         exercise: "2900 steps",
//         sleep: "8h 00m",
//       },
//     ],
//   },
//   {
//     id: "234567",
//     name: "Amir Kenth",
//     email: "skant@gmail.com",
//     avatarUrl: "",
//     patientId: "123456",
//     lastActive: "10/11/2024",
//     reminderStatus: "Sent",
//     pillStatus: "Not Filled",
//     isActive: true,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Not yet" },
//       { id: "2", date: "Yesterday", status: "Logged" },
//       { id: "3", date: "13/05/2025", status: "Logged" },
//       { id: "4", date: "12/05/2025", status: "Missed" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "110 mg/dL",
//         water: "500 ml",
//         meal: "120 g",
//         heartRate: "720 bpm",
//         exercise: "3000 steps",
//         sleep: "6h 30m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "125 mg/dL",
//         water: "650 ml",
//         meal: "130 g",
//         heartRate: "780 bpm",
//         exercise: "2800 steps",
//         sleep: "7h 15m",
//       },
//     ],
//   },
//   {
//     id: "345678",
//     name: "Mahmoud Alb",
//     email: "mahmoud@gmail.com",
//     avatarUrl: "/profile.jpg",
//     patientId: "654321",
//     lastActive: "10/10/2024",
//     reminderStatus: "Sent",
//     pillStatus: "Filled",
//     isActive: false,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Not yet" },
//       { id: "2", date: "Yesterday", status: "Missed" },
//       { id: "3", date: "13/05/2025", status: "Missed" },
//       { id: "4", date: "12/05/2025", status: "Logged" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "135 mg/dL",
//         water: "720 ml",
//         meal: "160 g",
//         heartRate: "790 bpm",
//         exercise: "2900 steps",
//         sleep: "8h 00m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "115 mg/dL",
//         water: "550 ml",
//         meal: "140 g",
//         heartRate: "760 bpm",
//         exercise: "2700 steps",
//         sleep: "7h 00m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//     ],
//   },
//   {
//     id: "456789",
//     name: "John Doe",
//     email: "john@gmail.com",
//     avatarUrl: "/profile.jpg",
//     patientId: "789012",
//     lastActive: "10/09/2024",
//     reminderStatus: "Not Sent",
//     pillStatus: "In Progress",
//     isActive: true,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Logged" },
//       { id: "2", date: "Yesterday", status: "Not yet" },
//       { id: "3", date: "13/05/2025", status: "Missed" },
//       { id: "4", date: "12/05/2025", status: "Logged" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "110 mg/dL",
//         water: "500 ml",
//         meal: "120 g",
//         heartRate: "720 bpm",
//         exercise: "3000 steps",
//         sleep: "6h 30m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "125 mg/dL",
//         water: "650 ml",
//         meal: "130 g",
//         heartRate: "780 bpm",
//         exercise: "2800 steps",
//         sleep: "7h 15m",
//       },
//     ],
//   },
//   {
//     id: "567890",
//     name: "Jane Smith",
//     email: "jane@gmail.com",
//     avatarUrl: "/profile.jpg",
//     patientId: "890123",
//     lastActive: "10/08/2024",
//     reminderStatus: "Sent",
//     pillStatus: "Filled",
//     isActive: true,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Logged" },
//       { id: "2", date: "Yesterday", status: "Logged" },
//       { id: "3", date: "13/05/2025", status: "Missed" },
//       { id: "4", date: "12/05/2025", status: "Logged" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "135 mg/dL",
//         water: "720 ml",
//         meal: "160 g",
//         heartRate: "790 bpm",
//         exercise: "2900 steps",
//         sleep: "8h 00m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "115 mg/dL",
//         water: "550 ml",
//         meal: "140 g",
//         heartRate: "760 bpm",
//         exercise: "2700 steps",
//         sleep: "7h 00m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//       {
//         id: "5",
//         date: "01/07/2024",
//         glucose: "125 mg/dL",
//         water: "650 ml",
//         meal: "130 g",
//         heartRate: "780 bpm",
//         exercise: "2800 steps",
//         sleep: "7h 15m",
//       },
//       {
//         id: "6",
//         date: "02/07/2024",
//         glucose: "115 mg/dL",
//         water: "550 ml",
//         meal: "140 g",
//         heartRate: "760 bpm",
//         exercise: "2700 steps",
//         sleep: "7h 00m",
//       },
//     ],
//   },
//   {
//     id: "678901",
//     name: "Alice Johnson",
//     email: "alice@gmail.com",
//     avatarUrl: "/profile.jpg",
//     patientId: "901234",
//     lastActive: "10/07/2024",
//     reminderStatus: "Sent",
//     pillStatus: "Not Filled",
//     isActive: true,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Not yet" },
//       { id: "2", date: "Yesterday", status: "Logged" },
//       { id: "3", date: "13/05/2025", status: "Missed" },
//       { id: "4", date: "12/05/2025", status: "Logged" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "110 mg/dL",
//         water: "500 ml",
//         meal: "120 g",
//         heartRate: "720 bpm",
//         exercise: "3000 steps",
//         sleep: "6h 30m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "125 mg/dL",
//         water: "650 ml",
//         meal: "130 g",
//         heartRate: "780 bpm",
//         exercise: "2800 steps",
//         sleep: "7h 15m",
//       },
//       {
//         id: "5",
//         date: "01/07/2024",
//         glucose: "115 mg/dL",
//         water: "550 ml",
//         meal: "140 g",
//         heartRate: "760 bpm",
//         exercise: "2700 steps",
//         sleep: "7h 00m",
//       },
//       {
//         id: "6",
//         date: "02/07/2024",
//         glucose: "135 mg/dL",
//         water: "720 ml",
//         meal: "160 g",
//         heartRate: "790 bpm",
//         exercise: "2900 steps",
//         sleep: "8h 00m",
//       },
//     ],
//   },
//   {
//     id: "789012",
//     name: "Bob Brown",
//     email: "bob.brown@gmail.com",
//     avatarUrl: "/profile.jpg",
//     patientId: "012345",
//     lastActive: "10/06/2024",
//     reminderStatus: "Not Sent",
//     pillStatus: "In Progress",
//     isActive: false,
//     fiillHistory: [
//       { id: "1", date: "Today", status: "Logged" },
//       { id: "2", date: "Yesterday", status: "Not yet" },
//       { id: "3", date: "13/05/2025", status: "Missed" },
//       { id: "4", date: "12/05/2025", status: "Logged" },
//     ],
//     healthLogs: [
//       {
//         id: "1",
//         date: "27/06/2024",
//         glucose: "135 mg/dL",
//         water: "720 ml",
//         meal: "160 g",
//         heartRate: "790 bpm",
//         exercise: "2900 steps",
//         sleep: "8h 00m",
//       },
//       {
//         id: "2",
//         date: "28/06/2024",
//         glucose: "115 mg/dL",
//         water: "550 ml",
//         meal: "140 g",
//         heartRate: "760 bpm",
//         exercise: "2700 steps",
//         sleep: "7h 00m",
//       },
//       {
//         id: "3",
//         date: "29/06/2024",
//         glucose: "130 mg/dL",
//         water: "700 ml",
//         meal: "150 g",
//         heartRate: "800 bpm",
//         exercise: "2500 steps",
//         sleep: "7h 45m",
//       },
//       {
//         id: "4",
//         date: "30/06/2024",
//         glucose: "120 mg/dL",
//         water: "600 ml",
//         meal: "100 g",
//         heartRate: "750 bpm",
//         exercise: "2113 steps",
//         sleep: "8h 30m",
//       },
//     ],
//   },
// ];

// export const statsData = {
//   totalUsers: { value: "150", percentage: "10%", trend: "up" },
//   newUsers: { value: "125", percentage: "10%", trend: "up" },
//   activeUsers: { value: "15", percentage: "10%", trend: "up" },
//   pendingReminders: { value: "5", percentage: "10%", trend: "down" },
// };

// export const sampleActivityData: Record<
//   "daily" | "weekly" | "monthly" | "yearly",
//   ActivityLogPoint[]
// > = {
//   daily: [
//     { name: "6 AM", uv: 1200 },
//     { name: "8 AM", uv: 2100 },
//     { name: "10 AM", uv: 3100 },
//     { name: "12 PM", uv: 1800 },
//     { name: "2 PM", uv: 2300 },
//     { name: "4 PM", uv: 2800 },
//     { name: "6 PM", uv: 1500 },
//     { name: "8 PM", uv: 1700 },
//   ],
//   weekly: [
//     { name: "Monday", uv: 5000 },
//     { name: "Tuesday", uv: 6000 },
//     { name: "Wednesday", uv: 7000 },
//     { name: "Thursday", uv: 8000 },
//     { name: "Friday", uv: 9000 },
//     { name: "Saturday", uv: 6500 },
//     { name: "Sunday", uv: 7200 },
//   ],
//   monthly : [
//     { name: "Week 1", uv: 7500 },
//     { name: "Week 2", uv: 8200 },
//     { name: "Week 3", uv: 6400 },
//     { name: "Week 4", uv: 9100 },
//   ],
//   yearly: [
//     { name: "Jan", uv: 32000 },
//     { name: "Feb", uv: 28000 },
//     { name: "Mar", uv: 35000 },
//     { name: "Apr", uv: 30000 },
//     { name: "May", uv: 40000 },
//     { name: "Jun", uv: 37000 },
//     { name: "Jul", uv: 42000 },
//     { name: "Aug", uv: 39000 },
//     { name: "Sep", uv: 36000 },
//     { name: "Oct", uv: 41000 },
//     { name: "Nov", uv: 45000 },
//     { name: "Dec", uv: 48000 },
//   ],
// };
